CREATE TABLE tb_pontos_registro
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data              date,
    hora_entrada      TIMESTAMP WITHOUT TIME ZONE,
    hora_saida        TIMESTAMP WITHOUT TIME ZONE,
    horas_trabalhadas time WITHOUT TIME ZONE,
    tipo_ponto        VARCHAR(255)                            NOT NULL,
    funcionario_id    BIGINT,
    CONSTRAINT pk_tb_pontos_registro PRIMARY KEY (id)
);

ALTER TABLE tb_pontos_registro
    ADD CONSTRAINT FK_TB_PONTOS_REGISTRO_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES tb_funcionario_registro (id);