CREATE TABLE tb_recrutamento
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo_vaga         VARCHAR(255),
    descricao_vaga      VARCHAR(255),
    data_abertura       date,
    data_encerramento   TIMESTAMP WITHOUT TIME ZONE,
    status_recrutamento VARCHAR(255),
    cargo_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_recrutamento PRIMARY KEY (id)
);

ALTER TABLE tb_recrutamento
    ADD CONSTRAINT FK_TB_RECRUTAMENTO_ON_CARGO FOREIGN KEY (cargo_id) REFERENCES tb_cargo_registro (id);