CREATE TABLE tb_treinamento_candidato
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_treinamento        VARCHAR(255),
    descricao_treinamento   VARCHAR(255),
    carga_horaria           INTEGER                                 NOT NULL,
    data_inicio_treinamento date                                    NOT NULL,
    data_fim_treinamento    date                                    NOT NULL,
    CONSTRAINT pk_tb_treinamento_candidato PRIMARY KEY (id)
);

CREATE TABLE treinamento_funcionario
(
    funcionario_id BIGINT NOT NULL,
    treinamento_id BIGINT NOT NULL
);

ALTER TABLE treinamento_funcionario
    ADD CONSTRAINT fk_trefun_on_funcionario_entity FOREIGN KEY (funcionario_id) REFERENCES tb_funcionario_registro (id);

ALTER TABLE treinamento_funcionario
    ADD CONSTRAINT fk_trefun_on_treinamento_entity FOREIGN KEY (treinamento_id) REFERENCES tb_treinamento_candidato (id);