CREATE TABLE tb_usuario_login
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_username     VARCHAR(255),
    login_password     VARCHAR(255),
    login_tipo_usuario VARCHAR(255),
    CONSTRAINT pk_tb_usuario_login PRIMARY KEY (id)
);