CREATE TABLE tb_avaliacao
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_avaliacao     date                                    NOT NULL,
    nota_avaliacao     INTEGER                                 NOT NULL,
    feedback_avaliacao VARCHAR(255),
    funcionario_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_avaliacao PRIMARY KEY (id)
);

ALTER TABLE tb_avaliacao
    ADD CONSTRAINT FK_TB_AVALIACAO_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES tb_funcionario_registro (id);