CREATE TABLE tb_entrevista_candidato
(
    candidato_id  BIGINT NOT NULL,
    entrevista_id BIGINT NOT NULL
);

CREATE TABLE tb_entrevista_recrutamento
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_entrevista        date,
    tipo_entrevista        VARCHAR(255),
    resultado_entrevista   VARCHAR(100)                            NOT NULL,
    observacoes_entrevista VARCHAR(255),
    recrutamento_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_entrevista_recrutamento PRIMARY KEY (id)
);

ALTER TABLE tb_entrevista_recrutamento
    ADD CONSTRAINT FK_TB_ENTREVISTA_RECRUTAMENTO_ON_RECRUTAMENTO FOREIGN KEY (recrutamento_id) REFERENCES tb_recrutamento (id);

ALTER TABLE tb_entrevista_candidato
    ADD CONSTRAINT fk_tbentcan_on_candidato_entity FOREIGN KEY (candidato_id) REFERENCES tb_candidato_registration (id);

ALTER TABLE tb_entrevista_candidato
    ADD CONSTRAINT fk_tbentcan_on_entrevista_entity FOREIGN KEY (entrevista_id) REFERENCES tb_entrevista_recrutamento (id);