CREATE TABLE tb_ferias_funcionario
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_inicio_ferias date                                    NOT NULL,
    data_fim_ferias    DOUBLE PRECISION                        NOT NULL,
    dias_ferias        INTEGER                                 NOT NULL,
    status_ferias      VARCHAR(255)                            NOT NULL,
    funcionario_id     BIGINT,
    CONSTRAINT pk_tb_ferias_funcionario PRIMARY KEY (id)
);

ALTER TABLE tb_ferias_funcionario
    ADD CONSTRAINT FK_TB_FERIAS_FUNCIONARIO_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES tb_funcionario_registro (id);