CREATE TABLE folha_pagamento_funcionario
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mes_ano_folha_pagamento         date                                    NOT NULL,
    salario_bruto_folha_pagamento   DOUBLE PRECISION                        NOT NULL,
    descontos_folha_pagamento       DOUBLE PRECISION                        NOT NULL,
    beneficios_folha_pagamento      VARCHAR(200)                            NOT NULL,
    salario_liquido_folha_pagamento DOUBLE PRECISION                        NOT NULL,
    data_pagamento_folha_pagamento  date                                    NOT NULL,
    funcionario_id                  BIGINT                                  NOT NULL,
    CONSTRAINT pk_folha_pagamento_funcionario PRIMARY KEY (id)
);

ALTER TABLE folha_pagamento_funcionario
    ADD CONSTRAINT FK_FOLHA_PAGAMENTO_FUNCIONARIO_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES tb_funcionario_registro (id);